export default {
  
  "login": "Sankalp1008",
    "id": 80205060,
      "node_id": "MDQ6VXNlcjgwMjA1MDYw",
        "avatar_url": "https://avatars.githubusercontent.com/u/80205060?v=4",
          "gravatar_id": "",
            "url": "https://api.github.com/users/Sankalp1008",
              "html_url": "https://github.com/Sankalp1008",
                "followers_url": "https://api.github.com/users/Sankalp1008/followers",
                  "following_url": "https://api.github.com/users/Sankalp1008/following{/other_user}",
                    "gists_url": "https://api.github.com/users/Sankalp1008/gists{/gist_id}",
                      "starred_url": "https://api.github.com/users/Sankalp1008/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/Sankalp1008/subscriptions",
                          "organizations_url": "https://api.github.com/users/Sankalp1008/orgs",
                            "repos_url": "https://api.github.com/users/Sankalp1008/repos",
                              "events_url": "https://api.github.com/users/Sankalp1008/events{/privacy}",
                                "received_events_url": "https://api.github.com/users/Sankalp1008/received_events",
                                  "type": "User",
                                    "site_admin": false,
                                      "name": "Sankalp Chaturvedi",
                                        "company": null,
                                          "blog": "",
                                            "location": "Ghaziabad,India",
                                              "email": null,
                                                "hireable": null,
                                                  "bio": "Just a passionate Web developer.",
                                                    "twitter_username": null,
                                                      "public_repos": 5,
                                                        "public_gists": 0,
                                                          "followers": 0,
                                                            "following": 2,
                                                              "created_at": "2021-03-07T13:14:22Z",
                                                                "updated_at": "2021-04-12T09:48:58Z"

};
